services:
  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    ports:
      - "9000:9000"
      - "8123:8123"
    environment:
      CLICKHOUSE_DB: fukan

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
